### ISSUE TITLE
Plugin not working on Japanese region 3.65 browser?

### ISSUE THREAD

**Issue by huckleberrypie** [GrapheneCt/UserAgentSpoofer#2]
I followed the instructions down to the letter, e.g. copied the requisite files to their folders, but a check on IPChicken.com still reports the same default user-agent as before.

**Comment by GrapheneCt** [comment]
[UserAgentSpoofer_test.zip](https://github.com/GrapheneCt/UserAgentSpoofer/files/10614131/UserAgentSpoofer_test.zip)
Please try again with this version. It should create log.bin file in ux0:data after running, upload it here.

**Comment by huckleberrypie** [comment]
> [UserAgentSpoofer_test.zip](https://github.com/GrapheneCt/UserAgentSpoofer/files/10614131/UserAgentSpoofer_test.zip) Please try again with this version. It should create log.bin file in ux0:data after running, upload it here.

Well this is very strange, I am not getting any log files at all, and yet I've already pasted the version you sent me along with the following lines at the bottom of config.txt:

*NPXS10083
ur0:tai/UserAgentSpoofer_test.suprx
*NPXS10084
ur0:tai/UserAgentSpoofer_test.suprx

Strange in that the other plugins I copied to ur0:/tai do work like the copy/paste tweak, but not this.

**Comment by huckleberrypie** [comment]
Anything?

**Comment by huckleberrypie** [comment]
Sorry for the bumps, but any updates?

**Comment by huckleberrypie** [comment]
NVM, installing ioplus solves the issue.
